import { ErrorCode, MyQError } from '../shared/errors';
import type { QueryResult, Row, SqlValue, TableDefinition } from '../shared/types';
import { CatalogService } from '../storage/CatalogService';
import type { StorageEngine } from '../storage/StorageEngine';
import { IndexManager } from '../indexes/IndexManager';
import { WalManager } from '../wal/WalManager';
import { SqlParser } from '../parser/SqlParser';
import type { BinaryExpressionNode, ExpressionNode, InsertNode, StatementNode } from '../parser/ast';
import type { Principal } from '../shared/types';
import { AuthService } from '../auth/AuthService';

export class QueryService {
  private writeQueue: Promise<void> = Promise.resolve();
  public constructor(private readonly parser: SqlParser, private readonly catalog: CatalogService, private readonly storage: StorageEngine, private readonly indexes: IndexManager, private readonly wal: WalManager, private readonly auth?: AuthService) {}
  public async execute(sql: string, database: string, principal: Principal): Promise<QueryResult> {
    const statement = this.parser.parse(sql);
    if ((statement.kind === 'createUser' || statement.kind === 'alterUser' || statement.kind === 'dropUser') && principal.role !== 'ADMIN') throw new MyQError(ErrorCode.FORBIDDEN, 'Administrator role required');
    switch (statement.kind) {
      case 'createDatabase': return this.withWriteLock(async () => { await this.catalog.createDatabase(statement.database); return { columns: [], rows: [], affectedRows: 1 }; });
      case 'createTable': return this.withWriteLock(() => this.createTable(database, statement));
      case 'dropTable': return this.withWriteLock(() => this.dropTable(database, statement.table));
      case 'insert': return this.withWriteLock(() => this.insert(database, statement));
      case 'select': return this.select(database, statement);
      case 'update': return this.withWriteLock(() => this.update(database, statement));
      case 'delete': return this.withWriteLock(() => this.delete(database, statement));
      case 'createUser': return this.withWriteLock(async () => { if (!this.auth) throw new MyQError(ErrorCode.INTERNAL, 'Authentication service is unavailable'); await this.auth.createUser(statement.username, statement.password); return this.userResult('CREATE_USER'); });
      case 'alterUser': return this.withWriteLock(async () => { if (!this.auth) throw new MyQError(ErrorCode.INTERNAL, 'Authentication service is unavailable'); await this.auth.alterPassword(statement.username, statement.password); return this.userResult('ALTER_USER'); });
      case 'dropUser': return this.withWriteLock(async () => { if (!this.auth) throw new MyQError(ErrorCode.INTERNAL, 'Authentication service is unavailable'); await this.auth.dropUser(statement.username); return this.userResult('DROP_USER'); });
    }
  }
  private async createTable(database: string, statement: Extract<StatementNode, { kind: 'createTable' }>): Promise<QueryResult> { if (!(await this.catalog.databaseExists(database))) throw new MyQError(ErrorCode.NOT_FOUND, `Database ${database} does not exist`); const primary = statement.columns.find((column) => column.primaryKey)?.name; if (!primary) throw new MyQError(ErrorCode.UNSUPPORTED, 'A primary key is required in Phase 1'); const definition: TableDefinition = { database, name: statement.table, columns: statement.columns, primaryKey: primary, uniqueColumns: statement.columns.filter((column) => column.unique).map((column) => column.name), schemaVersion: 1, createdAt: new Date().toISOString() }; await this.catalog.createTable(definition); this.indexes.createTableIndexes(definition); return { columns: [], rows: [], affectedRows: 1 }; }
  private async dropTable(database: string, table: string): Promise<QueryResult> { const definition = await this.catalog.getTable(database, table); for (const entry of await this.storage.scan(`row/${database}/${table}/`)) await this.storage.delete(entry.key); await this.catalog.dropTable(database, table); this.indexes.dropTableIndexes(definition); return { columns: [], rows: [], affectedRows: 1 }; }
  private async insert(database: string, statement: InsertNode): Promise<QueryResult> { const definition = await this.catalog.getTable(database, statement.table); const columns = statement.columns ?? definition.columns.map((column) => column.name); const rows: Array<{ primaryKey: string; row: Row }> = []; const pendingPrimaryKeys = new Set<string>(); const pendingUniqueValues = new Map<string, Set<string>>(); for (const column of definition.uniqueColumns) pendingUniqueValues.set(column, new Set()); for (const values of statement.values) { if (columns.length !== values.length) throw new MyQError(ErrorCode.UNSUPPORTED, 'Column and value counts do not match'); const row: Row = {}; columns.forEach((column, index) => { const value = values[index]?.value; if (value !== undefined) row[column] = value; }); this.validateRow(definition, row); const primaryKey = String(row[definition.primaryKey]); if (pendingPrimaryKeys.has(primaryKey)) throw new MyQError(ErrorCode.PRIMARY_KEY_CONFLICT, `Primary key ${primaryKey} is duplicated in the statement`); this.indexes.validateInsert(definition, primaryKey, row); for (const column of definition.uniqueColumns) { const value = row[column]; if (value !== null && value !== undefined) { const valuesForColumn = pendingUniqueValues.get(column) as Set<string>; if (valuesForColumn.has(String(value))) throw new MyQError(ErrorCode.UNIQUE_CONFLICT, `Unique value for ${column} is duplicated in the statement`); valuesForColumn.add(String(value)); } } pendingPrimaryKeys.add(primaryKey); rows.push({ primaryKey, row }); } let affected = 0; for (const item of rows) { const txnId = this.wal.newTransactionId(); const record = await this.wal.append({ txnId, operation: 'INSERT', database, table: statement.table, primaryKey: item.primaryKey, payload: item.row }); this.indexes.insert(definition, item.primaryKey, item.row); await this.storage.put(this.rowKey(database, statement.table, item.primaryKey), Buffer.from(JSON.stringify(item.row))); await this.wal.commit(txnId, record.lsn); affected += 1; } return { columns: [], rows: [], affectedRows: affected, lastInsertId: rows.at(-1)?.primaryKey }; }
  private async select(database: string, statement: Extract<StatementNode, { kind: 'select' }>): Promise<QueryResult> { const definition = await this.catalog.getTable(database, statement.table); const entries = await this.storage.scan(`row/${database}/${statement.table}/`); let rows = entries.map((entry) => JSON.parse(entry.value.toString('utf8')) as Row).filter((row) => !statement.where || evaluate(statement.where.expression, row)); if (statement.orderBy) rows.sort((left, right) => compareValues(left[statement.orderBy?.column ?? ''], right[statement.orderBy?.column ?? '']) * (statement.orderBy?.direction === 'DESC' ? -1 : 1)); if (statement.limit !== undefined) rows = rows.slice(0, statement.limit); const columns = statement.columns[0] === '*' ? definition.columns.map((column) => column.name) : statement.columns; return { columns, rows: rows.map((row) => Object.fromEntries(columns.map((column) => [column, row[column] ?? null]))) }; }
  private async update(database: string, statement: Extract<StatementNode, { kind: 'update' }>): Promise<QueryResult> { const definition = await this.catalog.getTable(database, statement.table); const entries = await this.storage.scan(`row/${database}/${statement.table}/`); const changes: Array<{ key: string; primaryKey: string; oldRow: Row; newRow: Row }> = []; for (const entry of entries) { const oldRow = JSON.parse(entry.value.toString('utf8')) as Row; if (statement.where && !evaluate(statement.where.expression, oldRow)) continue; const newRow = { ...oldRow }; for (const assignment of statement.assignments) newRow[assignment.column] = evaluateValue(assignment.value, oldRow); if (newRow[definition.primaryKey] !== oldRow[definition.primaryKey]) throw new MyQError(ErrorCode.UNSUPPORTED, 'Updating a primary key is not supported in Phase 1'); this.validateRow(definition, newRow); changes.push({ key: entry.key, primaryKey: String(oldRow[definition.primaryKey]), oldRow, newRow }); } let affected = 0; for (const change of changes) { const txnId = this.wal.newTransactionId(); const record = await this.wal.append({ txnId, operation: 'UPDATE', database, table: statement.table, primaryKey: change.primaryKey, payload: change.newRow }); this.indexes.update(definition, change.primaryKey, change.oldRow, change.newRow); await this.storage.put(change.key, Buffer.from(JSON.stringify(change.newRow))); await this.wal.commit(txnId, record.lsn); affected += 1; } return { columns: [], rows: [], affectedRows: affected }; }
  private async delete(database: string, statement: Extract<StatementNode, { kind: 'delete' }>): Promise<QueryResult> { const definition = await this.catalog.getTable(database, statement.table); const entries = await this.storage.scan(`row/${database}/${statement.table}/`); let affected = 0; for (const entry of entries) { const row = JSON.parse(entry.value.toString('utf8')) as Row; if (statement.where && !evaluate(statement.where.expression, row)) continue; const primaryKey = String(row[definition.primaryKey]); const txnId = this.wal.newTransactionId(); const record = await this.wal.append({ txnId, operation: 'DELETE', database, table: statement.table, primaryKey, payload: row }); this.indexes.delete(definition, primaryKey, row); await this.storage.delete(entry.key); await this.wal.commit(txnId, record.lsn); affected += 1; } return { columns: [], rows: [], affectedRows: affected }; }
  private userResult(operation: string): QueryResult { return { columns: ['operation'], rows: [{ operation }], affectedRows: 1 }; }
  private validateRow(definition: TableDefinition, row: Row): void { const knownColumns = new Set(definition.columns.map((column) => column.name)); for (const column of Object.keys(row)) if (!knownColumns.has(column)) throw new MyQError(ErrorCode.UNSUPPORTED, `Unknown column ${column}`); for (const column of definition.columns) { if (row[column.name] === undefined) row[column.name] = null; const value: SqlValue | undefined = row[column.name]; if (!column.nullable && value === null) throw new MyQError(ErrorCode.NOT_NULL, `Column ${column.name} cannot be null`); if (value !== null && value !== undefined && !this.matchesType(column.dataType, value)) throw new MyQError(ErrorCode.UNSUPPORTED, `Invalid value for ${column.name}`); } const primaryValue = row[definition.primaryKey]; if (primaryValue === null || primaryValue === undefined) throw new MyQError(ErrorCode.NOT_NULL, 'Primary key cannot be null'); }
  private matchesType(dataType: string, value: SqlValue): boolean { return (dataType === 'INT' && typeof value === 'number' && Number.isInteger(value)) || (dataType === 'VARCHAR' && typeof value === 'string') || (dataType === 'BOOLEAN' && typeof value === 'boolean') || (dataType === 'TIMESTAMP' && (typeof value === 'string' || value instanceof Date)); }
  private async withWriteLock(operation: () => Promise<QueryResult>): Promise<QueryResult> { const previous = this.writeQueue; let release!: () => void; this.writeQueue = new Promise<void>((resolve) => { release = resolve; }); await previous; try { return await operation(); } finally { release(); } }
  private rowKey(database: string, table: string, primaryKey: string): string { return `row/${database}/${table}/${primaryKey}`; }
}

function evaluate(expression: ExpressionNode, row: Row): boolean { if (expression.kind === 'binary') { const left = evaluateValue(expression.left, row); const right = evaluateValue(expression.right, row); if (expression.operator === 'AND') return Boolean(left) && Boolean(right); if (expression.operator === 'OR') return Boolean(left) || Boolean(right); const result = compareValues(left, right); return expression.operator === '=' ? result === 0 : expression.operator === '<>' ? result !== 0 : expression.operator === '<' ? result < 0 : expression.operator === '<=' ? result <= 0 : expression.operator === '>' ? result > 0 : result >= 0; } return Boolean(evaluateValue(expression, row)); }
function evaluateValue(expression: ExpressionNode, row: Row): SqlValue { return expression.kind === 'column' ? row[expression.name] ?? null : expression.kind === 'literal' ? expression.value : evaluate(expression, row); }
function compareValues(left: SqlValue | undefined, right: SqlValue | undefined): number { if (left === right) return 0; if (left === null || left === undefined) return -1; if (right === null || right === undefined) return 1; return left < right ? -1 : left > right ? 1 : 0; }
